# Generated by Django 5.1 on 2024-09-22 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmateapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='dept_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='role_id',
        ),
    ]
